# Generated by Django 5.1.1 on 2024-09-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Task2",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("modified", models.CharField(max_length=1000)),
            ],
        ),
    ]
