.PHONY: test

test:
    python -m unittest discover -s tests -p "test_*.py"


test_v: ## Run tests # -v = verbose
	python -m unittest discover -s tests -v  

# commmand line
#python -m unittest discover -s . -p "test_*.py"

