install:
	poetry install
	poetry add ruff
	poetry add black

#cria ambiente virtual
shell:
	poetry shell

#cria amb virtual que existe apenas durante a execução do script python
run:
	poetry run python src/main.py
